name: fly prerelease deployment test

# on: [push]
on:
  release:
    types: [prereleased]

env:
  FLY_API_TOKEN: ${{ secrets.TEST_FLY_TOKEN }}
  FLY_PROJECT_PATH: "./examples/fly-prerelease-deployment-test"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"
