name: netlify prerelease deployment test

# on:
#   release:
#     types: [prereleased]

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - run: npm ci
        working-directory: ./examples/netlify-prerelease-deployment-test
      - run: npm run build
        working-directory: ./examples/netlify-prerelease-deployment-test

      - name: Create Netlify Site
        working-directory: ./examples/netlify-prerelease-deployment-test
        run: |
          node ./deploy.mjs
